base_link:
  sensor_kit_base_link:
    x: 3.10
    y: 0.15
    z: 2.0
    roll: 0.000
    pitch: 0.00
    yaw: 1.575
  # velodyne_rear_base_link:
  #   x: -0.358
  #   y: 0.0
  #   z: 1.631
  #   roll: -0.02
  #   pitch: 0.7281317
  #   yaw: 3.141592
